name: Auto-commit changes
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run generator
        run: python scripts/generate_readme.py
      - name: Run reflection
        run: python scripts/generate_reflection.py
      - name: Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automated reflection update"
          branch: ${{ github.ref_name }}
